### ISSUE TITLE
Instructions on how to run it

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [midudev/covid-19-spread-simulator#2]
I downloaded the source but after opening `index.html` all I see is the image attached
<img width="1280" alt="Captura de pantalla 2020-03-18 a las 10 33 34" src="https://user-images.githubusercontent.com/9049533/76946294-1b7a3180-6904-11ea-9ca8-c7927da3d5d9.png">

What am I doing wrong?

Thanks in advance!

Rodrigo

**Comment by midudev** [comment]
Hey Rodrigo! Thanks! I'll add a README. :)

In your case, I think that the problem is that you're trying to open directly the index.html in your browser. As it's using modules, the `file://` protocol is not compatible. You need run the `index.html` with the server`.

There's an npm script that will start a local server for you. :)
Use as `npm run dev`.

**Comment by midudev** [comment]
I've added proper instructions in the README. Thanks!
